name: 📖 Bookdown

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'

jobs:
  bookdown:
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout
        uses: actions/checkout@v2

      - name: Cache Yarn packages
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: 💿 Install R
        uses: r-lib/actions/setup-r@main

      - name: 📦 Cache R packages
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-

      - name: 💿 Install Pandoc
        uses: r-lib/actions/setup-pandoc@v1

      - name: 💿 Install R packages
        run: |
          R -e "install.packages('bookdown')"

      - name: 🛠 Build site
        run: |
          ./build_html.R

      - name: 🚀 Deploy to build branch
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: build
          FOLDER: book
